### PR TITLE
[Feat] add camera

### PR DESCRIPTION
**Pull request by hanson-hschang**
Add feature #23.
- set up camera location
- set up camera look at location
- set up transparent film background

### CODE REVIEW

**Comment by skim0119** [comment]
@hanson-hschang Could you add simple example script?

**Comment by hanson-hschang** [comment]
https://github.com/user-attachments/assets/dc36e0a1-52ac-4493-8e1f-a772620302ad

**Comment by hanson-hschang** [comment]
`bsr.select_camera()` defined in `macros.py` is changed to `bsr.camera_manager.select()`

**Review by skim0119 — APPROVED** [review]
LGTM!

**Pull request merged**
